name: Build LaTeX document
on:
  push:
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          glob_root_file: true
          root_file: '**/*.tex'
          work_in_root_file_dir: true
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: pdf_files
          path: '**/*.pdf'
      # Automatically release artifacts
      - name: Automatic release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Release"
          files: |
            **/*.pdf
